services:
  scrapper.db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: imoveisdb
    ports:
      - 5432:5432
    volumes:
        - ./Scrapper.Lib/Db/init.sql:/docker-entrypoint-initdb.d/init.sql
  extractionsdb:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example    
    ports:
      - 27018:27017
#    volumes:
#      - mongodb_data_container:/data/db
  extractionsdb-gui:
    image: mongo-express
    restart: always
    ports:
      - 8082:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: passwdroot
      ME_CONFIG_MONGODB_URL: mongodb://root:example@extractionsdb:27017/
      ME_CONFIG_BASICAUTH: false
    depends_on:
      - extractionsdb
# docker run -d --hostname my-rabbit --name some-rabbit -e RABBITMQ_DEFAULT_USER=user -e RABBITMQ_DEFAULT_PASS=password rabbitmq:3-management

  scrapper.queue:
    image: rabbitmq:3-management
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=root
      - RABBITMQ_DEFAULT_PASS=passwd
    depends_on:
      - extractionsdb
      - scrapper.db
  
  scrapper.worker:
    image: ${DOCKER_REGISTRY-}scrapperworker
    build:
      context: .
      dockerfile: Scrapper.Worker/Dockerfile
    environment:
        IMOVEISSCRAPPER_CONNECTION_STRING: "User ID=postgres;Password=postgres;Host=scrapper.db;Port=5432;Database=imoveisdb;Pooling=true;"
        IMOVEISSCRAPPER_WEBENGINE_PATH: "/usr/bin/google-chrome"
    depends_on:
      - scrapper.queue      

  scrapper.web:
    image: ${DOCKER_REGISTRY-}scrapperweb
    build:
      context: .
      dockerfile: Scrapper.Web/Dockerfile
    environment:
        IMOVEISSCRAPPER_CONNECTION_STRING: "User ID=postgres;Password=postgres;Host=scrapper.db;Port=5432;Database=imoveisdb;Pooling=true;"
        IMOVEISSCRAPPER_WEBENGINE_PATH: "/usr/bin/google-chrome"    

#volumes:
#  mongodb_data_container: